source 'https://github.com/CocoaPods/Specs.git'

target 'JVMusicPlayer', :exclusive => true do
  pod "JVMusicPlayer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JVMusicPlayer", :path => "../"

  
end
